fix .rubocop.yml
bundle exec rake spec

Running RuboCop...
.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
/Users/blendthink/Documents/repositories/flutter-analyze-parser/.rubocop.yml: Warning: no department given for PercentLiteralDelimiters.
Error: The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentHash` cop has been renamed to `Layout/FirstHashElementIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentHeredoc` cop has been renamed to `Layout/HeredocIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Style/BracesAroundHashParameters` cop has been removed.
(obsolete configuration found in .rubocop.yml, please update it)
RuboCop failed!